[package]
name = "gbars"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
# raylib = { version = "5.5", default-features = false, features = ["nobuild"] }
minifb = "0.28"

# [build-dependencies]
# pkg-config = "0.3"
#
[dev-dependencies]
test-case = "*"
